# Site settings
title: Cadence Baker
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://memoriata.com" # the base hostname & protocol for your site

permalink: /blog/:title.html
sass:
    sass_dir: _sass

paginate: 4
paginate_path: "/blog/page:num/"
gems: [jekyll-paginate]

# Build settings
markdown: kramdown

page_gen:
  - data: 'audio-originalcomps'
    template: 'audio'
    name: 'title'
    dir: 'music/audio/originalcomps'
  - data: 'audio-playlist-concert2017-10-15'
    template: 'audio'
    name: 'title'
    dir: 'music/audio/pianorecs/concert2017-10-15'
  - data: 'audio-pianorecs'
    template: 'audio'
    name: 'title'
    dir: 'music/audio/pianorecs'
  - data: 'video-originalcomps'
    template: 'video'
    name: 'title'
    dir: 'music/video/originalcomps'
  - data: 'video-pianorecs'
    template: 'video'
    name: 'title'
    dir: 'music/video/pianorecs'
