# Site settings
title: memoriata.com 
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://memoriata.com" # the base hostname & protocol for your site

permalink: /blog/:title
sass:
    sass_dir: _sass

# Build settings
markdown: kramdown
